### PR TITLE
Feature: stream responses from chat engine

### LINKED ISSUE #14: Support streaming chat responses
### 🔍 Description

LlamaIndex chat engines [support streaming responses](https://docs.llamaindex.ai/en/stable/module_guides/deploying/chat_engines/root.html#usage-pattern). It would be a small UX improvement if rags could support streamlit the engines' responses to the Streamlit frontend such that users don't have to wait until the entire response is generated.

The only issue is that  `.streamlit_chat` is uses async functions. But Streamlit runs in a separate thread that doesn’t have an event loop by default. To make it work, the implementation will need to create an event loop and run the `.stream_chat` call inside it.

Happy to submit a PR for this!

### PR DESCRIPTION
**Pull request by snehankekre**
## 🔍  Description

Closes #14.

LlamaIndex chat engines [support streaming responses](https://docs.llamaindex.ai/en/stable/module_guides/deploying/chat_engines/root.html#usage-pattern). This PR implements streaming responses to the Streamlit frontend using `.stream_chat(prompt)` instead of `.chat(prompt)`.

cc @jerryjliu @carolinedlu

## ✨ After

https://github.com/run-llama/rags/assets/20672874/df6be856-0ec4-4b08-9b3f-11d91a21bf02

## 😐 Before

https://github.com/run-llama/rags/assets/20672874/5edef67f-3949-4426-9edc-8a6ecfe3e86e

### CODE REVIEW

**Comment by anoopshrma** [comment]
Hey @snehankekre
This would be a great addition!

**Review by jerryjliu — COMMENTED** [review]
this looks good! 

to make the code a tad less redundant, would you be able to:
-  put getting the event loop code block into a function
-  put both `async def generate_response` and event loop function into agent_utils.py, and just call it from home page and generated agent page?

**Comment by snehankekre** [comment]
Certainly! Thank you for the feedback 😃 

With  ac8567a, the event loop creation and response generation are now centralized as two functions in `agent_utils.py` that are called from the home page and the generated agent page. 

Is this what you had in mind? Lastly, lmk if I should remove these comments from both pages if you think they're redundant:

```
# Streamlit runs in a separate thread that doesn’t have an event loop by default
# Create an event loop and run the async function (generate_response) inside it
loop = get_or_create_event_loop()
```

**Review by skydiver1980 — APPROVED** [review]

**Comment by snehankekre** [comment]
I've resolved all conflicts. Looks ready to merge barring any blocking feedback

**Comment by snehankekre** [comment]
Closing due to being unable to resolve conflicts with `main` repeatedly.

**Pull request closed without merging**
